# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6c268d6f019643a607a7415729dc6075655e87b4359d645d3999ae3e082d6a4447aac2659a03b89db585712ac3f603f4a167999d67611767cb59cc64685ab8c

test:
  secret_key_base: ebf4596498919f8fbd7c69a3952165318388028583dc08c33a790139ca05a9aa69f66795c750fff4df565fad4d88d86a2289651bcb7745437b5feca35a856cd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
